version: "3.8"

networks:
  dev:
    driver: bridge

services:
  # Backend
  backend:
    image: cosmtrek/air:latest
    volumes:
      - ../backend:/app
    working_dir: /app
    command: sh -c "air"
    ports:
      - "8080:8080"
    networks:
      - dev
    logging:
      options:
        max-size: "1m"
        max-file: "3"

  # Frontend website
  website:
    image: node:22
    volumes:
      - ../website:/app
    working_dir: /app
    command: >
      sh -c "npm install -g pnpm &&
             pnpm install &&
             pnpm dev"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - dev
    logging:
      options:
        max-size: "1m"
        max-file: "3"

  # Nginx for reverse proxy
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - website
      - backend
    networks:
      - dev
    logging:
      options:
        max-size: "1m"
        max-file: "3" 
