version: "3.8"

networks:
  dev:
    driver: bridge

services:
  # Backend
  backend:
    image: cosmtrek/air:latest
    volumes:
      - ../backend:/app
    working_dir: /app
    command: sh -c "air"
    ports:
      - "8080:8080"
    networks:
      - dev

  # Frontend website
  website:
    image: node:22
    volumes:
      - ../website:/app
    working_dir: /app
    command: >
      sh -c "npm install -g pnpm &&
             pnpm install &&
             pnpm run dev --host 0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - dev

  # Nginx for reverse proxy
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - website
      - backend
    networks:
      - dev